language: node_js
script: npm run upload
branches:
  only:
  - master
env:
  secure: x1t+N0P0Xs4u3ScQlv2cGWGbVHxl8tUF4SCigQEY7jBvSIvq+wzf3Evdn/MnU6CLTt59Mf5w0pj7Il2UoMhpvbefITbt4JAKKJWNv6BpUA2I7RsrHiwVic4HZDF/VEHjAIy7EskzkRypldy1aFLAPK+kDPfUuoR6NF2sfto0mDZ4vmYdKHo6f9E7MzvtJLtV/+fwyLK/Psa5m1k2s9nIH95hSHev14UqhGEgUvJBwnWUsGZfbtKzU5FQmr85fCP7i2Si39XjXKbpE5NyuXMefO0MzhElIOwzNOeliwREV3/cStuLcMA5qNOpkALiDClBk8JXbOPqeqkINN5cDNCI531uGjgvnS1KSg8l9FzagqxMxGzl6kaVj33v+dEIJW+NW1XTQvhRJK9BCMGjZCL/P8OIcymsGIVJV7cs1JlJzNKaMe3jI236WR4RNI97Fk1NQsdXUNt2g5jVUn0SIAwctJ0z0xm2qdNSvmu/H66mffARSEO9sD3kY++j+lSRJ38n4A4WvDGu37xzF81JNx6OzUTrh2wiiBmeHtGIyA6R8zz4d7acrs06i/dtcBuwmDY2yc7qYgH/+CBhWA9m7ZJSNYoJd58KoePbuobOt/a0a1Bz4iDphyuUT0yg48P9EhgW9eU9xJvya3JvQ6U+4OoicR8BStCLvsqNb3/aR90XIns=
